#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication  $(getApplication)
rm -rf 0
cp -r 0.org 0

rm -rf proc*
overPimpleDyMFoam 2>&1 | tee log.overPimpleDyMFoam
