#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication  $(getApplication)

# serial 
overPimpleDyMFoam 2>&1 | tee log.overPimpleDyMFoam

# parallel
#rm -rf proc*
#decomposePar 2>&1 | tee log.decomposePar
#mpirun -np 12 overPimpleDyMFoam -parallel 2>&1 | tee log.overPimpleDyMFoam
